version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: wellness_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  event-service:
    build:
      context: .  # Use root so Docker sees everything
      dockerfile: event_service/Dockerfile

    container_name: event-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DOCKER_COMPOSE_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wellness_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  wellness-service:
    build:
      context: .
      dockerfile: wellness-service/Dockerfile
    container_name: wellness-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DOCKER_COMPOSE_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wellness_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  goal-tracking-service:
    build:
      context: ./goal-tracking-service
      dockerfile: Dockerfile
    container_name: goal-tracking-service
    ports:
      - "8083:8080"
#    depends_on:
#      - postgres
#      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DOCKER_COMPOSE_ENABLED: false
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wellness_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379

volumes:
  pgdata: